### ISSUE TITLE
[feature request] could there be a function calculating point to curve distance?

### ISSUE THREAD

**Issue by shi-yan** [dorianprill/brezel#5]
This is very useful for font rendering (generating signed distance field)

Thanks

**Comment by dorianprill** [comment]
Yes, there should be!
The library is still missing many practical helper functions, which I will add over time!
Other things like intersections are also planned.

**Comment by dorianprill** [comment]
distance_to_point() has been added for QuadraticBezier, CubicBezier, Bezier, BSpline
